=== shilang/E/erp-service/src/main/resources/reports/module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:m="http://www.orbitatech.com/schema/module" targetNamespace="http://www.orbitatech.com/schema/module" elementFormDefault="qualified">
	<xs:simpleType name="stringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="entityAttr">
		<xs:attribute name="name" type="m:stringType" use="required"/>
		<xs:attribute name="class" type="m:stringType" use="required"/>
	</xs:attributeGroup>
	<xs:element name="field">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="title" type="m:stringType" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fields">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="m:field" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="module">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="m:stringType"/>
				<xs:element name="master">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="m:fields"/>
						</xs:sequence>
						<xs:attributeGroup ref="m:entityAttr"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="entries" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="entry" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element ref="m:fields"/>
									</xs:sequence>
									<xs:attributeGroup ref="m:entityAttr"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== shilang/E/erp-service/src/main/java/com/cloud/erp/service/report/salesOutStockNoticeReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://www.orbitatech.com/schema/module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.orbitatech.com/schema/module module.xsd">
	<name>发货通知</name>
	<master name="master" class="com.cloud.erp.entities.table.SalesOutStock">
		<fields>
			<field title="状态">result</field>
			<field title="单据编号">billNo</field>
			<field title="日期">date</field>
			<field title="购货单位">customerName</field>
			<field title="运输方式">salesScopeName</field>
			<field title="销售方式">salesWayName</field>
			<field title="交货地点">fetchAddrName</field>
			<field title="仓库">stockName</field>
			<field title="主管">managerName</field>
			<field title="部门">deptName</field>
			<field title="业务员">employeeName</field>
			<field title="制单">createrName</field>
			<field title="结算方式">settlementName</field>
			<field title="审核人">checkerName</field>
			<field title="审核日期">checkDate</field>
			<field title="源单类型">sourceType</field>
			<field title="源单单号">sourceBillNo</field>
			<field title="摘要">explanation</field>
		</fields>
	</master>
	<entries>
		<entry name="entries" class="com.cloud.erp.entities.table.SalesOutStockEntry">
			<fields>
				<field title="产品代码">number</field>
				<field title="产品名称">itemName</field>
				<field title="规格型号">itemModel</field>
				<field title="单位">itemUnit</field>
				<field title="辅助属性">attrContent</field>
				<field title="数量">quantity</field>
				<field title="交货日期">fetchDate</field>
				<field title="仓库">stockId</field>
				<field title="源单单号">sourceBillNo</field>
				<field title="备注">remark</field>			
			</fields>	
		</entry>
	</entries>
</module>

=== shilang/E/erp-service/src/main/resources/reports/salesPriceListReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://www.orbitatech.com/schema/module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.orbitatech.com/schema/module module.xsd">
	<name>销售报价单</name>
	<master name="master" class="com.cloud.erp.entities.table.SalesPriceList">
		<fields>
			<field title="状态">result</field>
			<field title="单据编号">billNo</field>
			<field title="日期">date</field>
			<field title="购货单位">customerName</field>
			<field title="货币">currencyName</field>
			<field title="主管">managerName</field>
			<field title="部门">deptName</field>
			<field title="业务员">employeeName</field>
			<field title="制单">createrName</field>
			<field title="汇率">exchangeRate</field>
			<field title="审核人">checkerName</field>
			<field title="审核日期">checkDate</field>
		</fields>
	</master>
	<entries>
		<entry name="entries" class="com.cloud.erp.entities.table.SalesPriceListEntry">
			<fields>
				<field title="产品代码">number</field>
				<field title="产品名称">itemName</field>
				<field title="规格型号">itemModel</field>
				<field title="单位">itemUnit</field>
				<field title="辅助属性">attrContent</field>
				<field title="数量">quantity</field>
				<field title="单价">price</field>
				<field title="金额">amount</field>
				<field title="备注">remark</field>			
			</fields>	
		</entry>
	</entries>
</module>

=== shilang/E/erp-service/src/main/java/com/cloud/erp/service/report/salesOutStockReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://www.orbitatech.com/schema/module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.orbitatech.com/schema/module module.xsd">
	<name>销售出库</name>
	<master name="master" class="com.cloud.erp.entities.table.ICStockBill">
		<fields>
			<field title="状态">result</field>
			<field title="单据编号">billNo</field>
			<field title="日期">date</field>
			<field title="销售业务类型">marketingWayName</field>
			<field title="销售方式">salesWayName</field>
			<field title="交货地点">fetchAddrName</field>	
			<field title="发货仓库">stockName</field>	
			<field title="收款日期">settlementDate</field>
			<field title="发货">senderName</field>
			<field title="保管">defenderName</field>
			<field title="主管">managerName</field>
			<field title="部门">deptName</field>
			<field title="业务员">employeeName</field>
			<field title="制单">createrName</field>
			<field title="审核人">checkerName</field>
			<field title="审核日期">checkDate</field>
			<field title="源单类型">sourceType</field>
			<field title="源单单号">sourceBillNo</field>
			<field title="摘要">explanation</field>
		</fields>
	</master>
	<entries>
		<entry name="entries" class="com.cloud.erp.entities.table.ICStockBillEntry">
			<fields>
				<field title="产品代码">number</field>
				<field title="产品名称">itemName</field>
				<field title="规格型号">itemModel</field>
				<field title="单位">itemUnit</field>
				<field title="辅助属性">attrContent</field>
				<field title="应发数量">quantity</field>
				<field title="实发数量">actualQuantity</field>
				<field title="发货仓库">stockId</field>
				<field title="仓位">stockPlaceId</field>
				<field title="源单单号">sourceBillNo</field>
				<field title="备注">remark</field>			
			</fields>	
		</entry>
	</entries>
</module>

=== shilang/E/erp-service/src/main/resources/reports/salesOrderReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://www.orbitatech.com/schema/module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.orbitatech.com/schema/module module.xsd">
	<name>销售订单</name>
	<master name="master" class="com.cloud.erp.entities.table.SalesOrder">
		<fields>
			<field title="审核状态">result</field>
			<field title="订单状态">orderStatus</field>
			<field title="单据编号">billNo</field>
			<field title="日期">date</field>
			<field title="购货单位">customerName</field>
			<field title="销售方式">salesWayName</field>
			<field title="交货方式">fetchWayName</field>
			<field title="交货地点">fetchAddrName</field>
			<field title="交货日期">transitAheadTime</field>
			<field title="结算方式">settlementName</field>
			<field title="结算日期">settlementDate</field>
			<field title="币别">currencyName</field>
			<field title="汇率">exchangeRate</field>
			<field title="金额">amount</field>
			<field title="货运金额">freightAmount</field>
			<field title="贸易方式">tradeWayName</field>
			<field title="总金额">totalAmount</field>
			<field title="结算金额">settleAmount</field>
			<field title="银行费用">bankCost</field>
			<field title="结算币别">settleCurrencyName</field>
			<field title="结算状态">settleStatus</field>
			<field title="主管">managerName</field>
			<field title="部门">departmentName</field>
			<field title="业务员">employeeName</field>
			<field title="制单">createrName</field>
			<field title="审核人">checkerName</field>
			<field title="审核日期">checkDate</field>
			<field title="源单单号">sourceBillNo</field>
			<field title="源单类型">sourceType</field>
			<field title="摘要">explanation</field>
		</fields>
	</master>
	<entries>
		<entry name="entries" class="com.cloud.erp.entities.table.SalesOrderEntry">
			<fields>
				<field title="产品代码">number</field>
				<field title="产品名称">itemName</field>
				<field title="规格型号">itemModel</field>
				<field title="单位">itemUnit</field>
				<field title="辅助属性">attrContent</field>
				<field title="数量">quantity</field>
				<field title="单价">price</field>
				<field title="金额">amount</field>
				<field title="交货日期">date</field>
				<field title="建议交货日期">adviceDate</field>
				<field title="源单单号">sourceBillNo</field>
				<field title="备注">remark</field>			
			</fields>	
		</entry>
	</entries>
</module>

=== shilang/E/erp-service/src/main/java/com/cloud/erp/service/report/proceedsReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="http://www.orbitatech.com/schema/module"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.orbitatech.com/schema/module module.xsd">
	<name>应款单</name>
	<master name="master" class="com.cloud.erp.entities.table.RecProceeds">
		<fields>
			<field title="状态">result</field>
			<field title="单据编号">billNo</field>
			<field title="日期">date</field>
			<field title="核算项目类别">subject</field>
			<field title="核算项目">customerName</field>
			<field title="核算项目开户银行">custBank</field>
			<field title="核算项目银行账号">custBankNum</field>
			<field title="财务日期">settleDate</field>
			<field title="结算方式">settleName</field>
			<field title="币别">currencyName</field>
			<field title="汇率">exchangeRate</field>
			<field title="单据金额">amount</field>
			<field title="实收金额">settleAmount</field>
			<field title="银行费用">bankCost</field>
			<field title="实收币别">settleCurrencyName</field>
			<field title="收款银行">bank</field>
			<field title="账号">bankNum</field>
			<field title="摘要">explanation</field>
			<field title="部门">deptName</field>
			<field title="业务员">employeeName</field>
			<field title="制单">createrName</field>
			<field title="审核人">checkerName</field>
			<field title="审核日期">checkDate</field>
			<field title="源单单号">sourceBillNo</field>
			<field title="源单类型">sourceType</field>
			<field title="备注">remark</field>
		</fields>
	</master>
	<entries>
		<entry name="entries" class="com.cloud.erp.entities.table.RecProceedsEntry">
			<fields>
				<field title="产品代码">number</field>
				<field title="产品名称">itemName</field>
				<field title="规格型号">itemModel</field>
				<field title="单位">itemUnit</field>
				<field title="辅助属性">attrContent</field>
				<field title="数量">quantity</field>
				<field title="单价">price</field>
				<field title="金额">amount</field>
				<field title="结算数量">settleQty</field>
				<field title="结算实收金额">settleAmount</field>
				<field title="源单单号">sourceBillNo</field>
				<field title="备注">remark</field>			
			</fields>	
		</entry>
	</entries>
</module>
